package fr.acinq.lightning.payment

import fr.acinq.bitcoin.*
import fr.acinq.bitcoin.Script.tail
import fr.acinq.bitcoin.io.ByteArrayInput
import fr.acinq.bitcoin.io.ByteArrayOutput
import fr.acinq.bitcoin.utils.Either
import fr.acinq.bitcoin.utils.Try
import fr.acinq.bitcoin.utils.runTrying
import fr.acinq.lightning.*
import fr.acinq.lightning.Lightning.randomBytes32
import fr.acinq.lightning.utils.*
import fr.acinq.lightning.wire.LightningCodecs
import kotlin.experimental.and

/**
 * @param encodedAmount We counterintuitively store the string-serialized amount instead of the numeric value. The goal is to preserve the
 *                      validity of the signature for invoices generated by 3rd party software when the amount is not canonically encoded.
 */
data class Bolt11Invoice(
    val prefix: String,
    val encodedAmount: String,
    val timestampSeconds: Long,
    override val nodeId: PublicKey,
    val tags: List<TaggedField>,
    val signature: ByteVector
) : PaymentRequest() {
    constructor(prefix: String, amount: MilliSatoshi?, timestampSeconds: Long, nodeId: PublicKey, tags: List<TaggedField>, signature: ByteVector) : this(prefix, encodeAmount(amount), timestampSeconds, nodeId, tags, signature)

    override val amount: MilliSatoshi? = decodeAmount(encodedAmount)

    val chain: Chain? get() = prefixes.entries.firstOrNull { it.value == prefix }?.key

    override val paymentHash: ByteVector32 get() = tags.filterIsInstance<TaggedField.PaymentHash>().first().run { this.hash }
    val paymentSecret: ByteVector32 get() = tags.filterIsInstance<TaggedField.PaymentSecret>().first().run { this.secret }
    val paymentMetadata: ByteVector? get() = tags.filterIsInstance<TaggedField.PaymentMetadata>().firstOrNull()?.run { this.data }

    val description: String? get() = tags.filterIsInstance<TaggedField.Description>().firstOrNull()?.run { this.description }
    val descriptionHash: ByteVector32? get() = tags.filterIsInstance<TaggedField.DescriptionHash>().firstOrNull()?.run { this.hash }

    val expirySeconds: Long? get() = tags.filterIsInstance<TaggedField.Expiry>().firstOrNull()?.run { this.expirySeconds }
    val minFinalExpiryDelta: CltvExpiryDelta? get() = tags.filterIsInstance<TaggedField.MinFinalCltvExpiry>().firstOrNull()?.run { CltvExpiryDelta(this.cltvExpiryDelta) }

    val fallbackAddress: String? = tags.filterIsInstance<TaggedField.FallbackAddress>().firstOrNull { it.version < 19 }?.run { this.toAddress(prefix) }

    override val features: Features get() = tags.filterIsInstance<TaggedField.Features>().firstOrNull()?.run { Features(this.bits) } ?: Features.empty

    val routingInfo: List<TaggedField.RoutingInfo> = tags.filterIsInstance<TaggedField.RoutingInfo>()

    override val accountable: Boolean = tags.contains(TaggedField.Accountable)

    init {
        val f = features.invoiceFeatures()
        require(f.hasFeature(Feature.VariableLengthOnion)) { "${Feature.VariableLengthOnion.rfcName} must be supported" }
        require(f.hasFeature(Feature.PaymentSecret)) { "${Feature.PaymentSecret.rfcName} must be supported" }
        require(Features.validateFeatureGraph(f) == null)

        require(amount == null || amount > 0.msat) { "amount is not valid" }
        require(tags.filterIsInstance<TaggedField.PaymentHash>().size == 1) { "there must be exactly one payment hash tag" }
        require(tags.filterIsInstance<TaggedField.PaymentSecret>().size == 1) { "there must be exactly one payment secret tag" }
        require(description != null || descriptionHash != null) { "there must be exactly one description tag or one description hash tag" }
        routingInfo.forEach { require(it.hints.isNotEmpty()) { "routing hint must contain one or more entries" } }
    }

    override fun isExpired(currentTimestampSeconds: Long): Boolean = when (val expirySeconds = expirySeconds) {
        null -> timestampSeconds + DEFAULT_EXPIRY_SECONDS <= currentTimestampSeconds
        else -> timestampSeconds + expirySeconds <= currentTimestampSeconds
    }

    private fun hrp() = prefix + encodedAmount

    private fun rawData(): List<Int5> {
        val data5 = ArrayList<Int5>()
        data5.addAll(encodeTimestamp(timestampSeconds))
        tags
            .filterNot { it is TaggedField.Features && it.bits.isEmpty() }
            .forEach {
                val encoded = it.encode()
                val len = encoded.size
                data5.add(it.tag)
                data5.add((len / 32).toByte())
                data5.add((len.rem(32)).toByte())
                data5.addAll(encoded)
            }
        return data5
    }

    private fun signedPreimage(): ByteArray {
        return hrp().encodeToByteArray() + toByteArray(rawData())
    }

    private fun signedHash(): ByteVector32 = Crypto.sha256(signedPreimage()).toByteVector32()

    /**
     * Sign a payment request.
     *
     * @param privateKey private key, which must match the payment request's node id
     * @return a signature (64 bytes) plus a recovery id (1 byte)
     */
    fun sign(privateKey: PrivateKey): Bolt11Invoice {
        require(privateKey.publicKey() == nodeId) { "private key does not match node id" }
        val msg = signedHash()
        val sig = Crypto.sign(msg, privateKey)
        val (pub1, _) = Crypto.recoverPublicKey(sig, msg.toByteArray())
        val recid = if (nodeId == pub1) 0.toByte() else 1.toByte()
        return this.copy(signature = sig.concat(recid))
    }

    override fun write(): String {
        val signature5 = Bech32.eight2five(signature.toByteArray())
        return Bech32.encode(hrp(), rawData().toTypedArray() + signature5, Bech32.Encoding.Bech32)
    }

    companion object {
        const val DEFAULT_EXPIRY_SECONDS = 3600 // default value from Bolt 11
        val DEFAULT_MIN_FINAL_EXPIRY_DELTA = CltvExpiryDelta(18) // default value from Bolt 11

        private val prefixes = mapOf(
            Chain.Regtest to "lnbcrt",
            Chain.Testnet3 to "lntb",
            Chain.Testnet4 to "lntb",
            Chain.Mainnet to "lnbc"
        )

        fun create(
            chain: Chain,
            amount: MilliSatoshi?,
            paymentHash: ByteVector32,
            privateKey: PrivateKey,
            description: Either<String, ByteVector32>,
            minFinalCltvExpiryDelta: CltvExpiryDelta,
            features: Features,
            paymentSecret: ByteVector32 = randomBytes32(),
            paymentMetadata: ByteVector? = null,
            expirySeconds: Long? = null,
            extraHops: List<List<TaggedField.ExtraHop>> = listOf(),
            timestampSeconds: Long = currentTimestampSeconds()
        ): Bolt11Invoice {
            val prefix = prefixes[chain] ?: error("unknown chain hash")
            val tags = mutableListOf(
                TaggedField.PaymentHash(paymentHash),
                TaggedField.MinFinalCltvExpiry(minFinalCltvExpiryDelta.toInt()),
                TaggedField.PaymentSecret(paymentSecret),
                // We remove unknown features which could make the invoice too big.
                TaggedField.Features(features.invoiceFeatures().copy(unknown = setOf()).toByteArray().toByteVector()),
                TaggedField.Accountable
            )
            description.left?.let { tags.add(TaggedField.Description(it)) }
            description.right?.let { tags.add(TaggedField.DescriptionHash(it)) }
            paymentMetadata?.let { tags.add(TaggedField.PaymentMetadata(it)) }
            expirySeconds?.let { tags.add(TaggedField.Expiry(it)) }
            if (extraHops.isNotEmpty()) {
                extraHops.forEach { tags.add(TaggedField.RoutingInfo(it)) }
            }
            return Bolt11Invoice(
                prefix = prefix,
                encodedAmount = encodeAmount(amount),
                timestampSeconds = timestampSeconds,
                nodeId = privateKey.publicKey(),
                tags = tags,
                signature = ByteVector.empty
            ).sign(privateKey)
        }

        private fun decodeTimestamp(input: List<Int5>): Long = input.take(7).fold(0L) { a, b -> 32 * a + b }

        fun encodeTimestamp(input: Long): List<Int5> {
            tailrec fun loop(value: Long, acc: List<Int5>): List<Int5> = if (acc.size == 7) acc.reversed() else loop(value / 32, acc + value.rem(32).toByte())
            return loop(input, listOf())
        }

        fun read(input: String): Try<Bolt11Invoice> = runTrying {
            val (hrp, data) = Bech32.decode(input)
            val prefix = prefixes.values.find { hrp.startsWith(it) } ?: throw IllegalArgumentException("unknown prefix $hrp")
            val encodedAmount = hrp.drop(prefix.length)
            val timestamp = decodeTimestamp(data.toList())
            // signature and recovery id, encoded on 65 bytes = 5 * 13 bytes = 5 * 13 * 8 bits =  8 * 13 "5-bits integers"
            val sigandrecid = toByteArray(data.copyOfRange(data.size - 8 * 13, data.size).toList())
            val sig = sigandrecid.dropLast(1).toByteArray().toByteVector64()
            val recid = sigandrecid.last()
            val data1 = toByteArray(data.copyOfRange(0, data.size - 8 * 13).toList())
            val tohash = hrp.encodeToByteArray() + data1
            val msg = Crypto.sha256(tohash)

            val tags = ArrayList<TaggedField>()

            tailrec fun loop(input: List<Int5>) {
                if (input.isNotEmpty()) {
                    val tag = input[0]
                    val len = 32 * input[1] + input[2]
                    val value = input.drop(3).take(len)
                    when (tag) {
                        TaggedField.PaymentHash.tag -> tags.add(kotlin.runCatching { TaggedField.PaymentHash.decode(value) }.getOrDefault(TaggedField.InvalidTag(tag, value)))
                        TaggedField.PaymentSecret.tag -> tags.add(kotlin.runCatching { TaggedField.PaymentSecret.decode(value) }.getOrDefault(TaggedField.InvalidTag(tag, value)))
                        TaggedField.PaymentMetadata.tag -> tags.add(kotlin.runCatching { TaggedField.PaymentMetadata.decode(value) }.getOrDefault(TaggedField.InvalidTag(tag, value)))
                        TaggedField.Description.tag -> tags.add(kotlin.runCatching { TaggedField.Description.decode(value) }.getOrDefault(TaggedField.InvalidTag(tag, value)))
                        TaggedField.DescriptionHash.tag -> tags.add(kotlin.runCatching { TaggedField.DescriptionHash.decode(value) }.getOrDefault(TaggedField.InvalidTag(tag, value)))
                        TaggedField.Expiry.tag -> tags.add(kotlin.runCatching { TaggedField.Expiry.decode(value) }.getOrDefault(TaggedField.InvalidTag(tag, value)))
                        TaggedField.MinFinalCltvExpiry.tag -> tags.add(kotlin.runCatching { TaggedField.MinFinalCltvExpiry.decode(value) }.getOrDefault(TaggedField.InvalidTag(tag, value)))
                        TaggedField.FallbackAddress.tag -> tags.add(kotlin.runCatching { TaggedField.FallbackAddress.decode(value) }.getOrDefault(TaggedField.InvalidTag(tag, value)))
                        TaggedField.Features.tag -> tags.add(kotlin.runCatching { TaggedField.Features.decode(value) }.getOrDefault(TaggedField.InvalidTag(tag, value)))
                        TaggedField.RoutingInfo.tag -> tags.add(kotlin.runCatching { TaggedField.RoutingInfo.decode(value) }.getOrDefault(TaggedField.InvalidTag(tag, value)))
                        TaggedField.NodeId.tag -> tags.add(kotlin.runCatching { TaggedField.NodeId.decode(value) }.getOrDefault(TaggedField.InvalidTag(tag, value)))
                        TaggedField.Accountable.tag -> tags.add(if (value.isEmpty()) TaggedField.Accountable else TaggedField.UnknownTag(tag, value))
                        else -> tags.add(TaggedField.UnknownTag(tag, value))
                    }
                    loop(input.drop(3 + len))
                }
            }

            loop(data.drop(7).dropLast(104))

            val nodeId = when (val nodeIdTag = tags.filterIsInstance<TaggedField.NodeId>().firstOrNull()) {
                null -> {
                    // We use pubkey recovery to compute the node id from the message and signature, so we don't need to check the signature.
                    Crypto.recoverPublicKey(sig, msg, recid.toInt())
                }
                else -> {
                    // The nodeId is provided, so we must check the signature.
                    require(Crypto.verifySignature(msg, sig, nodeIdTag.pub)) { "invalid signature" }
                    nodeIdTag.pub
                }
            }
            val pr = Bolt11Invoice(prefix, encodedAmount, timestamp, nodeId, tags, sigandrecid.toByteVector())
            require(pr.signedPreimage().contentEquals(tohash)) { "invoice isn't canonically encoded" }
            pr
        }

        fun decodeAmount(input: String): MilliSatoshi? {
            val amount = when {
                input.isEmpty() -> null
                input.last() == 'p' -> {
                    require(input.endsWith("0p")) { "invalid sub-millisatoshi precision" }
                    MilliSatoshi(input.dropLast(1).toLong() / 10L)
                }
                input.last() == 'n' -> MilliSatoshi(input.dropLast(1).toLong() * 100L)
                input.last() == 'u' -> MilliSatoshi(input.dropLast(1).toLong() * 100_000L)
                input.last() == 'm' -> MilliSatoshi(input.dropLast(1).toLong() * 100_000_000L)
                else -> MilliSatoshi(input.toLong() * 100_000_000_000L)
            }
            return if (amount == MilliSatoshi(0)) null else amount
        }

        /**
         * @return the unit allowing for the shortest representation possible
         */
        fun unit(amount: MilliSatoshi): Char? {
            val pico = amount.toLong() * 10
            return when {
                pico.rem(1_000) > 0 -> 'p'
                pico.rem(1_000_000) > 0 -> 'n'
                pico.rem(1_000_000_000) > 0 -> 'u'
                pico.rem(1_000_000_000_000) > 0 -> 'm'
                else -> null
            }
        }

        fun encodeAmount(amount: MilliSatoshi?): String {
            return when {
                amount == null -> ""
                unit(amount) == 'p' -> "${amount.toLong() * 10}p" // 1 pico-bitcoin == 10 milli-satoshis
                unit(amount) == 'n' -> "${amount.toLong() / 100}n"
                unit(amount) == 'u' -> "${amount.toLong() / 100_000}u"
                unit(amount) == 'm' -> "${amount.toLong() / 100_000_000}m"
                unit(amount) == null -> "${amount.toLong() / 100_000_000_000}"
                else -> throw IllegalArgumentException("invalid amount $amount")
            }
        }

        fun toBits(value: Int5): List<Boolean> = listOf(
            (value and 16) != 0.toByte(),
            (value and 8) != 0.toByte(),
            (value and 4) != 0.toByte(),
            (value and 2) != 0.toByte(),
            (value and 1) != 0.toByte()
        )

        // converts a list of booleans (1 per bit) to a byte, right-padded if there are less than 8 bits
        internal fun toByte(bits: List<Boolean>): Byte {
            require(bits.size <= 8)
            val raw = bits.fold(0) { a, b -> 2 * a + if (b) 1 else 0 }
            val shift = 8 - bits.size
            return (raw.shl(shift) and 0xff).toByte()
        }

        // converts a list of 5 bits values to a byte array
        internal fun toByteArray(int5s: List<Int5>): ByteArray {
            val allbits = int5s.flatMap { toBits(it) }
            return allbits.windowed(8, 8, partialWindows = true) { toByte(it) }.toByteArray()
        }
    }

    sealed class TaggedField {
        abstract val tag: Int5
        abstract fun encode(): List<Int5>

        /** @param description a free-format string that will be included in the payment request */
        data class Description(val description: String) : TaggedField() {
            override val tag: Int5 = Description.tag
            override fun encode(): List<Int5> = Bech32.eight2five(description.encodeToByteArray()).toList()

            companion object {
                const val tag: Int5 = 13
                fun decode(input: List<Int5>): Description = Description(Bech32.five2eight(input.toTypedArray(), 0).decodeToString())
            }
        }

        /** @param hash sha256 hash of an associated description */
        data class DescriptionHash(val hash: ByteVector32) : TaggedField() {
            override val tag: Int5 = DescriptionHash.tag
            override fun encode(): List<Int5> = Bech32.eight2five(hash.toByteArray()).toList()

            companion object {
                const val tag: Int5 = 23
                fun decode(input: List<Int5>): DescriptionHash {
                    require(input.size == 52)
                    return DescriptionHash(Bech32.five2eight(input.toTypedArray(), 0).toByteVector32())
                }
            }
        }

        /** @param hash payment hash */
        data class PaymentHash(val hash: ByteVector32) : TaggedField() {
            override val tag: Int5 = PaymentHash.tag
            override fun encode(): List<Int5> = Bech32.eight2five(hash.toByteArray()).toList()

            companion object {
                const val tag: Int5 = 1
                fun decode(input: List<Int5>): PaymentHash {
                    require(input.size == 52)
                    return PaymentHash(Bech32.five2eight(input.toTypedArray(), 0).toByteVector32())
                }
            }
        }

        /** @param secret payment secret */
        data class PaymentSecret(val secret: ByteVector32) : TaggedField() {
            override val tag: Int5 = PaymentSecret.tag
            override fun encode(): List<Int5> = Bech32.eight2five(secret.toByteArray()).toList()

            companion object {
                const val tag: Int5 = 16
                fun decode(input: List<Int5>): PaymentSecret {
                    require(input.size == 52)
                    return PaymentSecret(Bech32.five2eight(input.toTypedArray(), 0).toByteVector32())
                }
            }
        }

        /** @param data metadata about the payment (see option_payment_metadata). */
        data class PaymentMetadata(val data: ByteVector) : TaggedField() {
            override val tag: Int5 = PaymentMetadata.tag
            override fun encode(): List<Int5> = Bech32.eight2five(data.toByteArray()).toList()

            companion object {
                const val tag: Int5 = 27
                fun decode(input: List<Int5>): PaymentMetadata = PaymentMetadata(Bech32.five2eight(input.toTypedArray(), 0).toByteVector())
            }
        }

        /** @param expirySeconds payment expiry (in seconds) */
        data class Expiry(val expirySeconds: Long) : TaggedField() {
            override val tag: Int5 = Expiry.tag
            override fun encode(): List<Int5> {
                tailrec fun loop(value: Long, acc: List<Int5>): List<Int5> = if (value == 0L) acc.reversed() else {
                    loop(value / 32, acc + (value.rem(32)).toByte())
                }
                return loop(expirySeconds, listOf())
            }

            companion object {
                const val tag: Int5 = 6
                fun decode(input: List<Int5>): Expiry {
                    var expiry = 0L
                    input.forEach { expiry = expiry * 32 + it }
                    return Expiry(expiry)
                }
            }
        }

        /** @param cltvExpiryDelta minimum final expiry delta */
        data class MinFinalCltvExpiry(val cltvExpiryDelta: Int) : TaggedField() {
            override val tag: Int5 = MinFinalCltvExpiry.tag
            override fun encode(): List<Int5> {
                tailrec fun loop(value: Int, acc: List<Int5>): List<Int5> = if (value == 0) acc.reversed() else {
                    loop(value / 32, acc + (value.rem(32)).toByte())
                }
                return loop(cltvExpiryDelta, listOf())
            }

            companion object {
                const val tag: Int5 = 24
                fun decode(input: List<Int5>): MinFinalCltvExpiry {
                    var expiry = 0
                    input.forEach { expiry = expiry * 32 + it }
                    return MinFinalCltvExpiry(expiry)
                }
            }
        }

        /** Fallback on-chain payment address to be used if LN payment cannot be processed */
        data class FallbackAddress(val version: Byte, val data: ByteVector) : TaggedField() {
            override val tag: Int5 = FallbackAddress.tag
            override fun encode(): List<Int5> = listOf(version) + Bech32.eight2five(data.toByteArray()).toList()

            fun toAddress(prefix: String): String = when (version.toInt()) {
                17 -> when (prefix) {
                    "lnbc" -> Base58Check.encode(Base58.Prefix.PubkeyAddress, data)
                    else -> Base58Check.encode(Base58.Prefix.PubkeyAddressTestnet, data)
                }
                18 -> when (prefix) {
                    "lnbc" -> Base58Check.encode(Base58.Prefix.ScriptAddress, data)
                    else -> Base58Check.encode(Base58.Prefix.ScriptAddressTestnet, data)
                }
                else -> when (prefix) {
                    "lnbc" -> Bech32.encodeWitnessAddress("bc", version, data.toByteArray())
                    "lntb" -> Bech32.encodeWitnessAddress("tb", version, data.toByteArray())
                    "lnbcrt" -> Bech32.encodeWitnessAddress("bcrt", version, data.toByteArray())
                    else -> throw IllegalArgumentException("unknown prefix $prefix")
                }
            }

            companion object {
                const val tag: Int5 = 9
                fun decode(input: List<Int5>): FallbackAddress = FallbackAddress(input.first(), Bech32.five2eight(input.tail().toTypedArray(), 0).toByteVector())
            }
        }

        data class Features(val bits: ByteVector) : TaggedField() {
            override val tag: Int5 = Features.tag

            override fun encode(): List<Int5> {
                // We pad left to a multiple of 5
                val padded = bits.toByteArray().toMutableList()
                while (padded.size * 8 % 5 != 0) {
                    padded.add(0, 0)
                }
                // Then we remove leading 0 bytes
                return Bech32.eight2five(padded.toByteArray()).dropWhile { it == 0.toByte() }
            }

            companion object {
                const val tag: Int5 = 5
                fun decode(input: List<Int5>): Features {
                    // We pad left to a multiple of 8
                    val padded = input.toMutableList()
                    while (padded.size * 5 % 8 != 0) {
                        padded.add(0, 0)
                    }
                    // Then we remove leading 0 bytes
                    val features = Bech32.five2eight(padded.toTypedArray(), 0).dropWhile { it == 0.toByte() }
                    return Features(features.toByteArray().toByteVector())
                }
            }
        }

        /**
         * Extra hop contained in RoutingInfoTag
         *
         * @param nodeId start of the channel
         * @param shortChannelId channel id
         * @param feeBase node fixed fee
         * @param feeProportionalMillionths node proportional fee
         * @param cltvExpiryDelta node cltv expiry delta
         */
        data class ExtraHop(
            val nodeId: PublicKey,
            val shortChannelId: ShortChannelId,
            val feeBase: MilliSatoshi,
            val feeProportionalMillionths: Long,
            val cltvExpiryDelta: CltvExpiryDelta
        )

        /** @param hints extra routing information for a private route */
        data class RoutingInfo(val hints: List<ExtraHop>) : TaggedField() {
            override val tag: Int5 = RoutingInfo.tag

            override fun encode(): List<Int5> {
                val out = ByteArrayOutput()
                hints.forEach {
                    LightningCodecs.writeBytes(it.nodeId.value, out)
                    LightningCodecs.writeU64(it.shortChannelId.toLong(), out)
                    LightningCodecs.writeU32(it.feeBase.toLong().toInt(), out)
                    LightningCodecs.writeU32(it.feeProportionalMillionths.toInt(), out)
                    LightningCodecs.writeU16(it.cltvExpiryDelta.toInt(), out)
                }
                return Bech32.eight2five(out.toByteArray()).toList()
            }

            companion object {
                const val tag: Int5 = 3

                fun decode(input: List<Int5>): RoutingInfo {
                    val stream = ByteArrayInput(Bech32.five2eight(input.toTypedArray(), 0))
                    val hints = ArrayList<ExtraHop>()
                    while (stream.availableBytes >= 51) {
                        val hint = ExtraHop(
                            PublicKey(LightningCodecs.bytes(stream, 33)),
                            ShortChannelId(LightningCodecs.u64(stream)),
                            MilliSatoshi(LightningCodecs.u32(stream).toLong()),
                            LightningCodecs.u32(stream).toLong(),
                            CltvExpiryDelta(LightningCodecs.u16(stream))
                        )
                        hints.add(hint)
                    }
                    return RoutingInfo(hints)
                }
            }
        }

        /** @param pub optional public key of the payee, when public key recovery from the signature isn't used. */
        data class NodeId(val pub: PublicKey) : TaggedField() {
            override val tag: Int5 = NodeId.tag
            override fun encode(): List<Int5> = Bech32.eight2five(pub.value.toByteArray()).toList()

            companion object {
                const val tag: Int5 = 19
                fun decode(input: List<Int5>): NodeId {
                    require(input.size == 53)
                    return NodeId(PublicKey(Bech32.five2eight(input.toTypedArray(), 0)))
                }
            }
        }

        /** Present if the recipient is willing to be held accountable for the timely resolution of HTLCs. */
        data object Accountable : TaggedField() {
            override val tag: Int5 = 31
            override fun encode(): List<Int5> = emptyList()
        }

        /** Unknown tag (may or may not be valid) */
        data class UnknownTag(override val tag: Int5, val value: List<Int5>) : TaggedField() {
            override fun encode(): List<Int5> = value.toList()
        }

        /** Tag that we know is not valid (value is of the wrong length for example) */
        data class InvalidTag(override val tag: Int5, val value: List<Int5>) : TaggedField() {
            override fun encode(): List<Int5> = value.toList()
        }
    }
}